### ISSUE TITLE
No new versions since Nov 17th.

### ISSUE THREAD

**Issue by elicwhite** [es-shims/es7-shim#22]
It looks like there has been a bunch of changes to this repo, including the removal of SIMD since Nov 17th. The last release, v5.0.0 was released then. Should we be expecting a new release?

**Comment by ljharb** [comment]
I'm still figuring out the best way to sunset/replace/continue-to-maintain this package, which is why I haven't published a new version yet. I'll do a bump after some cleanup, shortly.

**Comment by elicwhite** [comment]
Hmm. I might be missing some context here. This package seems valuable to us. Is there something else we should be using instead? Or is the challenge that you are trying to reduce the number of things you are maintaining?

**Comment by ljharb** [comment]
The "something else" would be what I might be creating instead :-)

The issue is that the name series "esX-shim" is both unsustainable (a new one every year) and unproductive (now that the spec is on a yearly release train, there will likely be a tiny number of polyfillable things, possibly zero, in any given year).

As it is, ES7/ES2016 only has one shimmable thing in it: `Array#includes`. ES2017 has three shimmable things so far, but I don't think it'd be useful to cut this package down to the one item, and then make `es8-shim` with those 3 plus the proposals, and then later, move the proposals into `es9-shim`, etc.

**Comment by ljharb** [comment]
v6.0.0 published.
